context:
  version: "5.1.2"

package:
  name: typescript-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/typescript-language-server/-/typescript-language-server-${{ version }}.tgz
  sha256: 952d8bdfeaa214f98f551805c2961d16de52bf8ee5e2870e6a649ebd28c2d8e1

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - typescript-language-server --help

about:
  license: MIT AND Apache-2.0
  license_file: LICENSE
  summary: TypeScript & JavaScript Language Server
  homepage: https://github.com/typescript-language-server/typescript-language-server
  repository: https://github.com/typescript-language-server/typescript-language-server

extra:
  recipe-maintainers:
    - danielnachun
