context:
  version: "5.2.0"

package:
  name: typescript-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/typescript-language-server/-/typescript-language-server-${{ version }}.tgz
  sha256: 06e039729a9ab90e42411c55066b537531600ea9ade6ff20e2f6b694a823d24d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - typescript-language-server --help

about:
  license: MIT AND Apache-2.0
  license_file: LICENSE
  summary: TypeScript & JavaScript Language Server
  homepage: https://github.com/typescript-language-server/typescript-language-server
  repository: https://github.com/typescript-language-server/typescript-language-server

extra:
  recipe-maintainers:
    - danielnachun
