context:
  version: "4.3.4"

package:
  name: typescript-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/typescript-language-server/-/typescript-language-server-${{ version }}.tgz
  sha256: 9a8aef1dd532f9b4b38087b002b949d9e761ab31fe1dc2f0bfe43ac223150385

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - typescript-language-server --help

about:
  license: MIT AND Apache-2.0
  license_file: LICENSE
  summary: TypeScript & JavaScript Language Server
  homepage: https://github.com/typescript-language-server/typescript-language-server
  repository: https://github.com/typescript-language-server/typescript-language-server

extra:
  recipe-maintainers:
    - danielnachun
