context:
  version: "6.0.1"

package:
  name: typescript-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/typescript-language-server/-/typescript-language-server-${{ version }}.tgz
  sha256: 85eabb9251d85d3798b247b2bc0895ca111d866bfbf59533f64b2461b0d8649f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - typescript-language-server --help

about:
  license: MIT AND Apache-2.0
  license_file: LICENSE
  summary: TypeScript & JavaScript Language Server
  homepage: https://github.com/typescript-language-server/typescript-language-server
  repository: https://github.com/typescript-language-server/typescript-language-server

extra:
  recipe-maintainers:
    - danielnachun
